### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by pepelucci** [punarinta/xroom.app-translations#5]
Line 42 in the English translation is as follows:

restartRequiredText: 'This setting affects to much stuff, a so a reload is required. That\'s quick, don\'t worry!',

Please change to --> too, and take away the a in front of the so 

Recommendation to change to:
restartRequiredText: 'This setting affects **too** much stuff, so a reload is required. That\'s quick, don\'t worry!',

**Comment by punarinta** [comment]
Fixed. Thanks!
