### ISSUE TITLE
Fixes for Greek translation el.js file

### ISSUE THREAD

**Issue by pepelucci** [punarinta/xroom.app-translations#6]
Hi, I have made some changes to the translation for the Greek language after reviewing it online. Please use the following code for the el.js file with relevant changes. 

[el.js.zip](https://github.com/punarinta/xroom.app-translations/files/4050725/el.js.zip)

**Comment by punarinta** [comment]
@pepelucci thank you!
Could you please next time do it in a form of a pull request? It's so much more convenient to manage.  :)

**Comment by punarinta** [comment]
Deployed.

**Comment by pepelucci** [comment]
> @pepelucci thank you!
> Could you please next time do it in a form of a pull request? It's so much more convenient to manage. :)

Yes. I wasn't sure how it was the best way :)
